version: '3'
services:
  redis: 
    image: redis:alpine
    container_name: sc-redis
    restart: always
    command: redis-server --requirepass jaspic@redis
    volumes:
      - ../data/redis:/data
    networks:
      - sc-net
    ports:
      - 6379:6379
    env_file: .env

  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: sc-rabbitmq
    restart: always
    volumes:
      - ../data/rabbitmq:/var/lib/rabbitmq/mnesia
    networks:
      - sc-net
    ports:
      - 5672:5672
      - 15672:15672
    env_file: .env

  mysql:
    image: mysql:5.7
    container_name: sc-mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - sc-net
    ports:
      - 3306:3306
    volumes:
      - ../data/mysql/conf:/etc/mysql/conf.d
      - ../data/mysql/lib:/var/lib/mysql
      - ../data/mysql/log:/var/log/mysql
      - ../auth/db:/docker-entrypoint-initdb.d
#      - ./init-db.sh:/docker-entrypoint-initdb.d
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: ${DATASOURCE_PASSWORD}
      MYSQL_USER: jaspic
      MYSQL_PASSWORD: Jaspic_mysql
      MYSQL_DATABASE: sc_auth
    env_file: .env

networks:
  sc-net:
    external: false